apiVersion: v1
kind: Service
metadata:
  name: myappservice
spec:
  type: NodePort
  ports:
  - port: 80          # Port exposed within the cluster
    targetPort: 8080  # Port on the pods
    nodePort: 31000   # Port accessible externally on each node
  selector:
    app: my-app  # Select pods with this label

